// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PastryShopOrders.Data;

#nullable disable

namespace PastryShopOrders.Migrations
{
    [DbContext(typeof(PastryShopContext))]
    [Migration("20230531111558_Init2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PastryShopOrders.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "Anna",
                            LastName = "Kowalska"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Karol",
                            LastName = "Suska"
                        },
                        new
                        {
                            ID = 3,
                            FirstName = "Anna",
                            LastName = "Sowińska"
                        });
                });

            modelBuilder.Entity("PastryShopOrders.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "Michał",
                            LastName = "Rataj"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Oliwia",
                            LastName = "Kozioł"
                        },
                        new
                        {
                            ID = 3,
                            FirstName = "Ewa",
                            LastName = "Wróbel"
                        });
                });

            modelBuilder.Entity("PastryShopOrders.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.ToTable("Order", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AcceptedAt = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientID = 1,
                            Comments = "text-Comments",
                            EmployeeID = 2
                        },
                        new
                        {
                            ID = 2,
                            AcceptedAt = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientID = 2,
                            EmployeeID = 2,
                            FulfilledAt = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            AcceptedAt = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientID = 3,
                            Comments = "text-Comments22",
                            EmployeeID = 3
                        });
                });

            modelBuilder.Entity("PastryShopOrders.Models.OrderPastry", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("PastryID")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Comme")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("OrderID", "PastryID");

                    b.HasIndex("PastryID");

                    b.ToTable("Order_Pastry", (string)null);

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            PastryID = 1,
                            Amount = 3,
                            Comme = "comme-text"
                        },
                        new
                        {
                            OrderID = 2,
                            PastryID = 2,
                            Amount = 2,
                            Comme = "comme-text2"
                        },
                        new
                        {
                            OrderID = 3,
                            PastryID = 3,
                            Amount = 1,
                            Comme = "comme-text3"
                        });
                });

            modelBuilder.Entity("PastryShopOrders.Models.Pastry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ID");

                    b.ToTable("Pastry", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Ciasto czekoladowe",
                            Price = 23.399999999999999,
                            Type = "Czekoladowe"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Ciasto truskawkowo-śmietankowe",
                            Price = 27.899999999999999,
                            Type = "Owocowe"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Ciasto czekoladowo-karmelowe",
                            Price = 34.5,
                            Type = "Czekoladowe"
                        });
                });

            modelBuilder.Entity("PastryShopOrders.Models.Order", b =>
                {
                    b.HasOne("PastryShopOrders.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastryShopOrders.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PastryShopOrders.Models.OrderPastry", b =>
                {
                    b.HasOne("PastryShopOrders.Models.Order", "Order")
                        .WithMany("OrderPastries")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastryShopOrders.Models.Pastry", "Pastry")
                        .WithMany("OrderPastries")
                        .HasForeignKey("PastryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Pastry");
                });

            modelBuilder.Entity("PastryShopOrders.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PastryShopOrders.Models.Employee", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PastryShopOrders.Models.Order", b =>
                {
                    b.Navigation("OrderPastries");
                });

            modelBuilder.Entity("PastryShopOrders.Models.Pastry", b =>
                {
                    b.Navigation("OrderPastries");
                });
#pragma warning restore 612, 618
        }
    }
}
